// <auto-generated />
using System;
using Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(StudentManagementDbContext))]
    [Migration("20251213080601_r")]
    partial class r
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Batch", b =>
                {
                    b.Property<Guid>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BatchDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BatchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BatchTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BatchId");

                    b.HasIndex("BranchId");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("Domain.Models.Branch", b =>
                {
                    b.Property<Guid>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BranchId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("Domain.Models.College", b =>
                {
                    b.Property<Guid>("CollegeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CollegeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CollegeId");

                    b.ToTable("Colleges");
                });

            modelBuilder.Entity("Domain.Models.Course", b =>
                {
                    b.Property<Guid>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CourseFee")
                        .HasColumnType("float");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstallmentCount")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Domain.Models.CourseDetails", b =>
                {
                    b.Property<Guid>("CourseDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("StudentProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseDetailId");

                    b.HasIndex("BatchId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentProfileId");

                    b.ToTable("CourseDetails");
                });

            modelBuilder.Entity("Domain.Models.Experience", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TotalExperience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExperienceId");

                    b.HasIndex("StudentId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("Domain.Models.Fee", b =>
                {
                    b.Property<Guid>("FeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Amount")
                        .HasColumnType("float");

                    b.Property<double?>("AmountReceived")
                        .HasColumnType("float");

                    b.Property<DateTime?>("AmountReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("CurrentReceivedAmount")
                        .HasColumnType("float");

                    b.Property<double?>("DueAmount")
                        .HasColumnType("float");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<Guid>("FeeStructureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InstallmentNumber")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentMode")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("FeeId");

                    b.HasIndex("FeeStructureId");

                    b.ToTable("Fees");
                });

            modelBuilder.Entity("Domain.Models.FeeStructure", b =>
                {
                    b.Property<Guid>("InstallmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseDetailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalInstallment")
                        .HasColumnType("int");

                    b.HasKey("InstallmentId");

                    b.HasIndex("CourseDetailId");

                    b.HasIndex("StudentId");

                    b.ToTable("FeeStructures");
                });

            modelBuilder.Entity("Domain.Models.Qualification", b =>
                {
                    b.Property<Guid>("QualificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CollegeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PassOutYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QualificationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("QualificationId");

                    b.HasIndex("CollegeId");

                    b.HasIndex("StudentId");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("Domain.Models.QualificationMaster", b =>
                {
                    b.Property<Guid>("QualificationListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QualificationDiscription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QualificationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QualificationListId");

                    b.ToTable("QualificationMaster");
                });

            modelBuilder.Entity("Domain.Models.RegistrationFee", b =>
                {
                    b.Property<Guid>("RegistrationFeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Fee")
                        .HasColumnType("float");

                    b.Property<DateTime?>("FeeReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FeeStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("TrialStudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RegistrationFeeId");

                    b.HasIndex("TrialStudentId")
                        .IsUnique();

                    b.ToTable("RegistrationFees");
                });

            modelBuilder.Entity("Domain.Models.ReturnFee", b =>
                {
                    b.Property<int>("ReturnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReturnId"));

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ReturnAmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReturnMode")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReturnId");

                    b.HasIndex("StudentId");

                    b.ToTable("ReturnFees");
                });

            modelBuilder.Entity("Domain.Models.SecondaryContact", b =>
                {
                    b.Property<Guid>("SecondaryContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuardianName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SecondaryContactId");

                    b.HasIndex("StudentId");

                    b.ToTable("SecondaryContacts");
                });

            modelBuilder.Entity("Domain.Models.StudentProfile", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DOB")
                        .HasColumnType("date");

                    b.Property<byte[]>("Documents")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EnrollmentType")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFullyPaid")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReferredBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentReferenceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TrialStudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("studentStatus")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("BatchId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CourseId");

                    b.HasIndex("TrialStudentId");

                    b.ToTable("StudentProfiles");
                });

            modelBuilder.Entity("Domain.Models.Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("TransactionAmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TrialStudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TransactionId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TrialStudentId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Domain.Models.TrialStudent", b =>
                {
                    b.Property<Guid>("TrialStudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("studentStatus")
                        .HasColumnType("int");

                    b.HasKey("TrialStudentId");

                    b.HasIndex("CourseId");

                    b.ToTable("TrialStudents");
                });

            modelBuilder.Entity("Domain.Models.Batch", b =>
                {
                    b.HasOne("Domain.Models.Branch", "Branch")
                        .WithMany("Batches")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Domain.Models.CourseDetails", b =>
                {
                    b.HasOne("Domain.Models.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Models.Course", "Course")
                        .WithMany("CourseDetails")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Models.StudentProfile", "Profile")
                        .WithMany("Course")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Batch");

                    b.Navigation("Course");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Domain.Models.Experience", b =>
                {
                    b.HasOne("Domain.Models.StudentProfile", "Profile")
                        .WithMany("Experience")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Domain.Models.Fee", b =>
                {
                    b.HasOne("Domain.Models.FeeStructure", "FeeStructure")
                        .WithMany("FeeInstallment")
                        .HasForeignKey("FeeStructureId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FeeStructure");
                });

            modelBuilder.Entity("Domain.Models.FeeStructure", b =>
                {
                    b.HasOne("Domain.Models.CourseDetails", "CourseDetail")
                        .WithMany()
                        .HasForeignKey("CourseDetailId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Models.StudentProfile", "StudentProfile")
                        .WithMany("FeeStructure")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CourseDetail");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("Domain.Models.Qualification", b =>
                {
                    b.HasOne("Domain.Models.College", "College")
                        .WithMany("Qualifications")
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.StudentProfile", "Profile")
                        .WithMany("Qualification")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("College");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Domain.Models.RegistrationFee", b =>
                {
                    b.HasOne("Domain.Models.TrialStudent", "TrialStudent")
                        .WithOne("RegistrationFee")
                        .HasForeignKey("Domain.Models.RegistrationFee", "TrialStudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TrialStudent");
                });

            modelBuilder.Entity("Domain.Models.ReturnFee", b =>
                {
                    b.HasOne("Domain.Models.StudentProfile", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Domain.Models.SecondaryContact", b =>
                {
                    b.HasOne("Domain.Models.StudentProfile", "StudentProfile")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("Domain.Models.StudentProfile", b =>
                {
                    b.HasOne("Domain.Models.Batch", null)
                        .WithMany("StudentProfiles")
                        .HasForeignKey("BatchId");

                    b.HasOne("Domain.Models.Branch", "Branch")
                        .WithMany("StudentProfiles")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Models.Course", null)
                        .WithMany("StudentProfiles")
                        .HasForeignKey("CourseId");

                    b.HasOne("Domain.Models.TrialStudent", "TrialStudent")
                        .WithMany()
                        .HasForeignKey("TrialStudentId");

                    b.Navigation("Branch");

                    b.Navigation("TrialStudent");
                });

            modelBuilder.Entity("Domain.Models.Transaction", b =>
                {
                    b.HasOne("Domain.Models.StudentProfile", "StudentProfile")
                        .WithMany()
                        .HasForeignKey("StudentId");

                    b.HasOne("Domain.Models.TrialStudent", "TrialStudent")
                        .WithMany()
                        .HasForeignKey("TrialStudentId");

                    b.Navigation("StudentProfile");

                    b.Navigation("TrialStudent");
                });

            modelBuilder.Entity("Domain.Models.TrialStudent", b =>
                {
                    b.HasOne("Domain.Models.Course", "Courses")
                        .WithMany()
                        .HasForeignKey("CourseId");

                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Domain.Models.Batch", b =>
                {
                    b.Navigation("StudentProfiles");
                });

            modelBuilder.Entity("Domain.Models.Branch", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("StudentProfiles");
                });

            modelBuilder.Entity("Domain.Models.College", b =>
                {
                    b.Navigation("Qualifications");
                });

            modelBuilder.Entity("Domain.Models.Course", b =>
                {
                    b.Navigation("CourseDetails");

                    b.Navigation("StudentProfiles");
                });

            modelBuilder.Entity("Domain.Models.FeeStructure", b =>
                {
                    b.Navigation("FeeInstallment");
                });

            modelBuilder.Entity("Domain.Models.StudentProfile", b =>
                {
                    b.Navigation("Course");

                    b.Navigation("Experience");

                    b.Navigation("FeeStructure");

                    b.Navigation("Qualification");
                });

            modelBuilder.Entity("Domain.Models.TrialStudent", b =>
                {
                    b.Navigation("RegistrationFee");
                });
#pragma warning restore 612, 618
        }
    }
}
